---
galaxy_info:
  role_name: posix_hardening_tmp
  namespace: posix
  author: POSIX Hardening Team
  description: Temporary directory hardening with secure mount options
  company: Internal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Kali
      versions:
        - all
    - name: RedHat
      versions:
        - 8
        - 9
  galaxy_tags:
    - security
    - hardening
    - posix
    - tmp
    - mount
    - filesystem

dependencies:
  - role: posix_hardening_files
