---
galaxy_info:
  role_name: posix_hardening_services
  namespace: posix
  author: POSIX Hardening Team
  description: Service disabling hardening to reduce attack surface by stopping unnecessary services
  company: Internal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Kali
      versions:
        - all
    - name: RedHat
      versions:
        - 8
        - 9
  galaxy_tags:
    - security
    - hardening
    - posix
    - services
    - systemd
    - attack-surface

dependencies:
  - role: posix_hardening_firewall
