---
galaxy_info:
  role_name: posix_hardening_coredump
  namespace: posix
  author: POSIX Hardening Team
  description: Core dump hardening to prevent information disclosure in crash dumps
  company: Internal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Kali
      versions:
        - all
    - name: RedHat
      versions:
        - 8
        - 9
  galaxy_tags:
    - security
    - hardening
    - posix
    - coredump
    - core
    - dumps

dependencies:
  - role: posix_hardening_limits
